apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/rewrite-target: /
  name: piano-chat
spec:
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: piano-chat
          servicePort: http
        path: {{ .Values.ingress.path }}
      - backend:
          serviceName: piano-chat
          servicePort: ws
        path: {{ .Values.ingress.path }}/ws
