apiVersion: v1
kind: Service
metadata:
  name: piano-chat
spec:
  selector:
    app.kubernetes.io/name: piano-chat
  ports:
    - name: http
      port: 80
    - name: ws
      port: 6789
  type: ClusterIP
