name: ci

on:
  push:
    branches: 
      - master
    tags:
      - 'v*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta server
        id: docker_meta_server
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: lenstr/piano-chat-server
          tag-sha: true # add git short SHA as Docker tag
      -
        name: Docker meta www
        id: docker_meta_www
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: lenstr/piano-chat-www
          tag-sha: true # add git short SHA as Docker tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push server
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/server.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.docker_meta_server.outputs.tags }}
          labels: ${{ steps.docker_meta_server.outputs.labels }}
      -
        name: Build and push www
        id: docker_build_www
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/www.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.docker_meta_www.outputs.tags }}
          labels: ${{ steps.docker_meta_www.outputs.labels }}
      -
        name: Image digest server
        run: echo ${{ steps.docker_build_server.outputs.digest }}
      -
        name: Image digest www
        run: echo ${{ steps.docker_build_www.outputs.digest }}