name: ci

on:
  push:
    branches: 
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push server
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/server.Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: lenstr/piano-chat-server:latest
      -
        name: Build and push www
        id: docker_build_www
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/www.Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: lenstr/piano-chat-www:latest
      -
        name: Image digest server
        run: echo ${{ steps.docker_build_server.outputs.digest }}
      -
        name: Image digest www
        run: echo ${{ steps.docker_build_www.outputs.digest }}